
import { StyleSheet } from "react-native";
import { Fonts } from "../Theme/FontsSize";
import { Colours } from "../Theme/Colours/Color";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        flex: 1,
    },
    myLocationButton: {
        position: 'absolute',
        bottom: 280,
        right: 16,
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: Colours.white,
        justifyContent: 'center',
        alignItems: 'center',

        shadowColor: Colours.Black,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        zIndex: 5,
    },
    markerWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        height: 60,
        width: 40,
    },
    pinContainer: {
        position: 'absolute',
        bottom: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    pinShadow: {
        width: 14,
        height: 4,
        borderRadius: 7,
        backgroundColor: Colours.Black,
        position: 'absolute',
        bottom: 10,
    },
    bottomSheet: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    bottomSheetContent: {
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 20,
    },
    addressHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    addressTitle: {
        fontSize: 18,
        fontFamily: Fonts.MontserrateRegular,
        color: Colours.Black,
    },
    addressText: {
        fontSize: 15,
        fontFamily: Fonts.MontserrateRegular,
        color: Colours.mediumGray,
        lineHeight: 22,
    },
    searchResultsContainer: {
        position: 'absolute',
        top: 60,
        left: 0,
        right: 0,
        backgroundColor: Colours.white,
        borderRadius: 10,
        maxHeight: 250,
        zIndex: 9999,

        shadowColor: Colours.Black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    searchResultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        borderBottomWidth: 0.5,
        borderBottomColor: Colours.BoneWhite,
        gap: 10,
    },
    searchResultText: {
        fontSize: 14,
        color: Colours.charcoal,
        flex: 1,
    },
    inputLabel: {
        fontSize: 14,
        fontFamily: Fonts.MontserrateSemiBold,
        color: Colours.Black,
        marginBottom: 6,
    },
    textInput: {
        height: 48,
        borderWidth: 1,
        borderColor: Colours.BoneWhite,
        backgroundColor: Colours.BoneWhite,
        borderRadius: 12,
        paddingHorizontal: 16,
        fontSize: 15,
        color: Colours.Black,
        fontFamily: Fonts.MontserrateRegular,
    },
    tagContainer: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 4,
    },
    tagButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        height: 44,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colours.BoneWhite,
        backgroundColor: Colours.white,
    },
    tagButtonSelected: {
        borderColor: Colours.btnColours,
        backgroundColor: Colours.btnColours,
    },
    tagText: {
        fontSize: 14,
        fontFamily: Fonts.MontserrateSemiBold,
        color: Colours.mediumGray,
    },
    tagTextSelected: {
        color: Colours.white,
    },
    cancelButton: {
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        fontFamily: Fonts.MontserrateSemiBold,
        fontSize: 15,
        color: Colours.mediumGray,
    },
});